### ISSUE TITLE
Feature Request: Compatibility with the Examine Tooltip hub plugin

### ISSUE THREAD

**Issue by ShaunDreclin** [PolishToaster/patch-payment#1]
https://github.com/Cyborger1/examine-tooltip

Support for both the examine and check options would be good, but just examine would get the job done too. Cross-posted this to their repo

**Comment by PolishToaster** [comment]
I was able to add compatibility for the Examine option on my end by just changing the chat message tags. I'll have to look into getting the Check option to work as well, but I submitted an update request for the current changes. Thanks for the suggestion!

**Comment by Cyborger1** [comment]
I'm assuming it works, but prevents the actual examine message from showing up, right? I've been racking my brain with this and I don't see any easy way to allow one examine event to take in more than one text response without introducing a bunch of edge cases.

I do have one proposition to make that would be very simple.

In my plugin, I have some logic to isolate "Price of" messages and display them separately as tooltips (no rs3 boxes) since I can't easily attach those to an examine event. I could do the same thing with this plugin by checking these strings as Regexes.

```
// Regexes
"^A farmer will watch over an? .+ patch for"
"^An? .+ patch can NOT be protected by a farmer"
```

The messages would only be able to appear under the mouse and not attach to the objects in the interfaces, but since this would not rely on a previous "examine" or "check" click, this would work for both. However, the assumption here is that the phrasing never changes on this plugin's side.

Edit: I have implemented it this way and it seems to work. The code is on [this branch](https://github.com/Cyborger1/examine-tooltip/tree/patch-payment).

Just a question: In my config for this, should I refer to you as Zaaack (the name you put as the author of this plugin) or PolishToaster?

**Comment by PolishToaster** [comment]
Sorry for the late reply. I don't plan on changing the wording of those game messages so your solution would work. If you want to update the plugin with your changes that'd be up to you. Currently it works with the "Check with Examine" option which fulfills the purpose of the Examine Tooltip option.

Also I guess we'll stick with PolishToaster for the  name
